[package]
name = "openex"
version = "0.0.1"
edition = "2024"

[dependencies]
smol_str = "0.3.4"
slotmap = "1"
getopts-macro = "0.1.8"
expect-test = "1.5.1"
linked-hash-map = "0.5.6"

[profile.release]
debug = false
strip = true
lto = true
