[package]
name = "openex"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
smol_str = "0.3.4"
slotmap = "1"

[profile.release]
debug = false
strip = true
lto = true
